window.CZML_DEMOS = {
  "mosquito-rockcreek": {
    title: "Mosquito: Rock Creek",
    kicker: "Mosquito fire",
    description: "Run 10 smoke and cloud output loaded from the Mosquito Rock Creek camera set.",
    referenceImage: "czmlDemoFiles/czmlImages/mosquito-rockcreek/reference.jpg",
    smoke: "czmlDemoFiles/CZMLs/mosquito-rockcreek/smoke.czml",
    clouds: "czmlDemoFiles/CZMLs/mosquito-rockcreek/clouds.czml",
    cameraRange: 30000,
    cameraHeadingDegrees: 180,
    cameraPitchDegrees: -4,
    pointPixelSize: 10,
    particleAlphaMultiplier: 0.2,
    elevationAlphaFloor: 0.22,
    fillerPointsPerParticle: 55,
    maxFillerPoints: 42000,
    fillerTimeSamples: 32,
    fillerSpreadMeters: 360,
    fillerNearestDistanceBias: 720,
    fillerBrownianMetersPerSecond: 11,
    fillerBrownianMaxOffsetMeters: 55
  },
  "electra-redcorall": {
    title: "Electra: Red Corall",
    kicker: "Electra fire",
    description: "Run 6 smoke and cloud output loaded from the Electra Red Corall camera set.",
    referenceImage: "czmlDemoFiles/czmlImages/electra-redcorall/reference.jpg",
    smoke: "czmlDemoFiles/CZMLs/electra-redcorall/smoke.czml",
    clouds: "czmlDemoFiles/CZMLs/electra-redcorall/clouds.czml",
    cameraRange: 30000,
    cameraHeadingDegrees: 28,
    cameraPitchDegrees: -4,
    pointPixelSize: 10,
    particleAlphaMultiplier: 0.12,
    elevationAlphaFloor: 0.1,
    fillerPointsPerParticle: 55,
    maxFillerPoints: 42000,
    fillerTimeSamples: 32,
    fillerSpreadMeters: 360,
    fillerNearestDistanceBias: 720,
    fillerBrownianMetersPerSecond: 11,
    fillerBrownianMaxOffsetMeters: 55
  },
  "summit-meadowlakes": {
    title: "Summit Fire: Meadow Lakes",
    kicker: "Summit fire",
    description: "Run 5 smoke and cloud output loaded from the Summit Fire Meadow Lakes camera set.",
    referenceImage: "czmlDemoFiles/czmlImages/summit-meadowlakes/reference.jpg",
    smoke: "czmlDemoFiles/CZMLs/summit-meadowlakes/smoke.czml",
    clouds: "czmlDemoFiles/CZMLs/summit-meadowlakes/clouds.czml",
    cameraRange: 6400,
    cameraHeadingDegrees: 152,
    cameraPitchDegrees: -4,
    pointPixelSize: 10,
    particleAlphaMultiplier: 0.42,
    elevationAlphaFloor: 0.22,
    fillerPointsPerParticle: 55,
    maxFillerPoints: 42000,
    fillerTimeSamples: 32,
    fillerSpreadMeters: 360,
    fillerNearestDistanceBias: 720,
    fillerBrownianMetersPerSecond: 11,
    fillerBrownianMaxOffsetMeters: 55
  }
};

window.CESIUM_ION_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzZTIxNDU1ZC04NmQxLTQ2OWEtYTlkZS1kNTUzMDQ1ZWU5MjAiLCJpZCI6MTI2ODkwLCJpYXQiOjE2Nzc3MDI5Nzd9.Z_aKhzurjeaSidN2Ogwz2-VBQIdvYOhzzO2ui0dWN6s";
window.CESIUM_ENABLE_TERRAIN = true;
